[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "./deployments" }]
broadcast = "deployments"

[etherscan]
mainnet = { key = "${BLOCK_EXPLORER_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${BLOCK_EXPLORER_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
anvil = "http://localhost:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
